using HCI_Task.Server.Entities;
using Microsoft.EntityFrameworkCore.Migrations;
using System.Drawing;

namespace HCI_Task.Server.Migrations
{
    public static class DataSeeder
    {
        public static void SeedInitialData(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "Users",
                columns: ["Id", "UserName", "Password", "CreatedAt", "UpdatedAt"],
                values: new object[,]
                {
                    {"1","hci_admin","password",DateTime.Now,DateTime.Now},
                    {"2","customer_01","password",DateTime.Now,DateTime.Now},
                    {"3","customer_02","password",DateTime.Now,DateTime.Now},
                    {"4","customer_03","password",DateTime.Now,DateTime.Now},
                    {"5","customer_04","password",DateTime.Now,DateTime.Now},
                });

            migrationBuilder.InsertData(
                table: "Hospitals",
                columns: ["Id", "Name", "City", "CreatedAt", "UpdatedAt"],
                values: new object[,]
                {
                    {"1","City General Hospital","Waterford", DateTime.Now, DateTime.Now},
                    {"2","Grace Memorial Hospital","Galway", DateTime.Now, DateTime.Now},
                    {"3","Central Medical Center","Dublin", DateTime.Now, DateTime.Now},
                    {"4","Sunnydale Medical Center","Galway", DateTime.Now, DateTime.Now},
                    {"5","Forest Hills Hospital","Dublin", DateTime.Now, DateTime.Now},
                    {"6","Cedar Grove Hospital","Naas", DateTime.Now, DateTime.Now},
                    {"7","Brookside Regional Hospital","Waterford", DateTime.Now, DateTime.Now},
                    {"8","Oakwood Hospital","Naas", DateTime.Now, DateTime.Now},
                    {"9","Pineview Medical Center","Swords", DateTime.Now, DateTime.Now},
                    {"10","Brookside Regional Hospital","Swords", DateTime.Now, DateTime.Now},
                    {"11","Forest Hills Hospital","Swords", DateTime.Now, DateTime.Now},
                    {"12","Pineview Medical Center","Galway", DateTime.Now, DateTime.Now},
                    {"13","Sunset Community Hospital","Naas", DateTime.Now, DateTime.Now},
                    {"14","City General Hospital","Dublin", DateTime.Now, DateTime.Now},
                    {"15","St. John's Hospital","Swords", DateTime.Now, DateTime.Now},
                    {"16","Riverdale General Hospital","Dublin", DateTime.Now, DateTime.Now},
                    {"17","Cedar Grove Hospital","Waterford", DateTime.Now, DateTime.Now},
                    {"18","Meadowbrook Medical Center","Limerick", DateTime.Now, DateTime.Now},
                    {"19","Brookside Regional Hospital","Naas", DateTime.Now, DateTime.Now},
                    {"20","Pineview Medical Center","Swords", DateTime.Now, DateTime.Now},
                });
            migrationBuilder.InsertData(
                table: "UserHospitals",
                columns: ["Id", "UserId", "HospitalId", "UserRole", "CreatedAt", "UpdatedAt"],
                values: new object[,]
                {
                    {"1","1","1", "0", DateTime.Now, DateTime.Now},
                    {"2","1","2", "0", DateTime.Now, DateTime.Now},
                    {"3","1","3", "0", DateTime.Now, DateTime.Now},
                    {"4","1","4", "0", DateTime.Now, DateTime.Now},
                    {"5","2","1", "0", DateTime.Now, DateTime.Now},
                    {"6","2","2", "0", DateTime.Now, DateTime.Now},
                    {"7","2","9", "0", DateTime.Now, DateTime.Now},
                    {"8","2","10", "0", DateTime.Now, DateTime.Now},
                    {"9","3","5", "0", DateTime.Now, DateTime.Now},
                    {"10","3","6", "0", DateTime.Now, DateTime.Now},
                    {"11","3","7", "0", DateTime.Now, DateTime.Now},
                    {"12","4","1", "0", DateTime.Now, DateTime.Now},
                    {"13","4","12", "0", DateTime.Now, DateTime.Now},
                    {"14","4","13", "0", DateTime.Now, DateTime.Now},
                    {"15","4","15", "0", DateTime.Now, DateTime.Now},
                    {"16","4","19", "0", DateTime.Now, DateTime.Now},
                    {"17","4","20", "0", DateTime.Now, DateTime.Now},
                    {"18","1","5", "0", DateTime.Now, DateTime.Now},
                    {"19","1","6", "0", DateTime.Now, DateTime.Now},
                    {"20","1","7", "0", DateTime.Now, DateTime.Now},
                    {"21","1","8", "0", DateTime.Now, DateTime.Now},
                    {"22","1","9", "0", DateTime.Now, DateTime.Now},
                    {"23","1","10", "0", DateTime.Now, DateTime.Now},
                    {"24","1","11", "0", DateTime.Now, DateTime.Now},
                    {"25","1","12", "0", DateTime.Now, DateTime.Now},
                    {"26","1","13", "0", DateTime.Now, DateTime.Now},
                    {"27","1","14", "0", DateTime.Now, DateTime.Now},
                    {"28","1","15", "0", DateTime.Now, DateTime.Now},
                    {"29","1","16", "0", DateTime.Now, DateTime.Now},
                    {"30","1","17", "0", DateTime.Now, DateTime.Now},
                    {"31","1","18", "0", DateTime.Now, DateTime.Now},
                    {"32","1","19", "0", DateTime.Now, DateTime.Now},
                    {"33","1","20", "0", DateTime.Now, DateTime.Now},

                });

            migrationBuilder.InsertData(
                table: "Patients",
                columns: ["Id", "Name", "BirthDate", "CreatedAt", "UpdatedAt"],
                values: new object[,]
    {
                    {"1","Lindsey Gave",new DateOnly(1982,02,24), DateTime.Now, DateTime.Now},
                    {"2","Magdalen Huckster",new DateOnly(1990,04,27), DateTime.Now, DateTime.Now},
                    {"3","Yasmin Yuryichev",new DateOnly(2002,08,02), DateTime.Now, DateTime.Now},
                    {"4","Rollie Awcoate",new DateOnly(2010,02,21), DateTime.Now, DateTime.Now},
                    {"5","Hilton Cathie",new DateOnly(1982,06,03), DateTime.Now, DateTime.Now},
                    {"6","Aeriela Worling",new DateOnly(1980,03,20), DateTime.Now, DateTime.Now},
                    {"7","Dorette Piotrowski",new DateOnly(1992,08,11), DateTime.Now, DateTime.Now},
                    {"8","Guthrey Davidy",new DateOnly(2020,06,28), DateTime.Now, DateTime.Now},
                    {"9","Kurtis Starbuck",new DateOnly(1981,05,28), DateTime.Now, DateTime.Now},
                    {"10","Natala Wye",new DateOnly(2008,07,20), DateTime.Now, DateTime.Now},
                    {"11","Marjorie Boak",new DateOnly(2001,04,05), DateTime.Now, DateTime.Now},
                    {"12","Carmelle Mandel",new DateOnly(2020,06,11), DateTime.Now, DateTime.Now},
                    {"13","Hester De Ruggero",new DateOnly(1993,03,15), DateTime.Now, DateTime.Now},
                    {"14","Oralla Arents",new DateOnly(1993,02,08), DateTime.Now, DateTime.Now},
                    {"15","Jaymie Toe",new DateOnly(1980,05,02), DateTime.Now, DateTime.Now},
                    {"16","Ase Seeney",new DateOnly(1983,09,19), DateTime.Now, DateTime.Now},
                    {"17","Gertie Hilbourne",new DateOnly(2002,11,09), DateTime.Now, DateTime.Now},
                    {"18","Francoise Cankett",new DateOnly(2016,03,30), DateTime.Now, DateTime.Now},
                    {"19","Hanan Verheyden",new DateOnly(1993,05,17), DateTime.Now, DateTime.Now},
                    {"20","Chandler Torrecilla",new DateOnly(2010,12,15), DateTime.Now, DateTime.Now},
                    {"21","Jacklyn Godridge",new DateOnly(1996,09,12), DateTime.Now, DateTime.Now},
                    {"22","Colleen Chopin",new DateOnly(1997,05,23), DateTime.Now, DateTime.Now},
                    {"23","Jeramie Leamon",new DateOnly(2002,05,26), DateTime.Now, DateTime.Now},
                    {"24","Frederick Sneesby",new DateOnly(2006,07,07), DateTime.Now, DateTime.Now},
                    {"25","Bab Pingston",new DateOnly(2015,11,21), DateTime.Now, DateTime.Now},
                    {"26","Ken Kiddey",new DateOnly(1983,06,14), DateTime.Now, DateTime.Now},
                    {"27","Melanie Filasov",new DateOnly(2012,01,12), DateTime.Now, DateTime.Now},
                    {"28","Catlee Danilin",new DateOnly(2005,02,12), DateTime.Now, DateTime.Now},
                    {"29","Walden Orta",new DateOnly(2003,07,30), DateTime.Now, DateTime.Now},
                    {"30","Jacynth Clausen",new DateOnly(2022,01,30), DateTime.Now, DateTime.Now},
                    {"31","Hettie Fulger",new DateOnly(2023,09,15), DateTime.Now, DateTime.Now},
                    {"32","Michal Bevan",new DateOnly(1990,01,29), DateTime.Now, DateTime.Now},
                    {"33","Caryl Sargeaunt",new DateOnly(1986,10,11), DateTime.Now, DateTime.Now},
                    {"34","Arman Sizland",new DateOnly(2011,02,22), DateTime.Now, DateTime.Now},
                    {"35","Thibaud Barkly",new DateOnly(1993,11,17), DateTime.Now, DateTime.Now},
                    {"36","Cedric Wilding",new DateOnly(1994,06,26), DateTime.Now, DateTime.Now},
                    {"37","Robbert Sprackling",new DateOnly(2001,12,22), DateTime.Now, DateTime.Now},
                    {"38","Iormina Weedall",new DateOnly(2013,08,30), DateTime.Now, DateTime.Now},
                    {"39","Jacquette Weben",new DateOnly(1991,12,27), DateTime.Now, DateTime.Now},
                    {"40","Antonietta West",new DateOnly(2021,08,16), DateTime.Now, DateTime.Now},
                    {"41","Gabi McAnellye",new DateOnly(2001,04,17), DateTime.Now, DateTime.Now},
                    {"42","Stacia Bremner",new DateOnly(2010,08,15), DateTime.Now, DateTime.Now},
                    {"43","Daffie Varren",new DateOnly(2020,04,16), DateTime.Now, DateTime.Now},
                    {"44","Marlowe Prozescky",new DateOnly(2007,12,07), DateTime.Now, DateTime.Now},
                    {"45","Sheena Davidof",new DateOnly(2010,06,13), DateTime.Now, DateTime.Now},
                    {"46","Wyndham Jiruca",new DateOnly(1991,05,29), DateTime.Now, DateTime.Now},
                    {"47","Sibylle Bubbins",new DateOnly(2006,01,18), DateTime.Now, DateTime.Now},
                    {"48","Florette Batha",new DateOnly(2015,09,10), DateTime.Now, DateTime.Now},
                    {"49","Carol-jean Cressingham",new DateOnly(1980,10,01), DateTime.Now, DateTime.Now},
                    {"50","Derk Sabbins",new DateOnly(1990,07,10), DateTime.Now, DateTime.Now},
                    
                });

            migrationBuilder.InsertData(
              table: "Visits",
              columns: ["Id", "Description", "PatientId", "HospitalId", "CreatedAt", "UpdatedAt"],
              values: new object[,]
              {
                    {"1","Nunc rhoncus dui vel sem.","39","11", DateTime.Now, DateTime.Now},
                    {"2","Nulla tempus.","50","3", DateTime.Now, DateTime.Now},
                    {"3","Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","50","15", DateTime.Now, DateTime.Now},
                    {"4","Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.","5","7", DateTime.Now, DateTime.Now},
                    {"5","Aliquam sit amet diam in magna bibendum imperdiet.","34","6", DateTime.Now, DateTime.Now},
                    {"6","Vivamus tortor. Duis mattis egestas metus.","23","7", DateTime.Now, DateTime.Now},
                    {"7","Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.","20","20", DateTime.Now, DateTime.Now},
                    {"8","Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.","43","16", DateTime.Now, DateTime.Now},
                    {"9","In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.","37","12", DateTime.Now, DateTime.Now},
                    {"10","Morbi a ipsum.","8","10", DateTime.Now, DateTime.Now},
                    {"11","Sed vel enim sit amet nunc viverra dapibus.","32","18", DateTime.Now, DateTime.Now},
                    {"12","Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.","3","2", DateTime.Now, DateTime.Now},
                    {"13","Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.","17","11", DateTime.Now, DateTime.Now},
                    {"14","Morbi a ipsum.","28","6", DateTime.Now, DateTime.Now},
                    {"15","","24","17", DateTime.Now, DateTime.Now},
                    {"16","Aliquam non mauris. Morbi non lectus.","18","2", DateTime.Now, DateTime.Now},
                    {"17","","48","9", DateTime.Now, DateTime.Now},
                    {"18","Donec posuere metus vitae ipsum. Aliquam non mauris.","47","20", DateTime.Now, DateTime.Now},
                    {"19","Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.","19","14", DateTime.Now, DateTime.Now},
                    {"20","Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.","32","17", DateTime.Now, DateTime.Now},
                    {"21","In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.","45","9", DateTime.Now, DateTime.Now},
                    {"22","In sagittis dui vel nisl. Duis ac nibh.","29","20", DateTime.Now, DateTime.Now},
                    {"23","Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.","20","6", DateTime.Now, DateTime.Now},
                    {"24","Integer ac neque. Duis bibendum.","4","7", DateTime.Now, DateTime.Now},
                    {"25","Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.","42","6", DateTime.Now, DateTime.Now},
                    {"26","Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.","5","18", DateTime.Now, DateTime.Now},
                    {"27","Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.","20","20", DateTime.Now, DateTime.Now},
                    {"28","Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.","12","1", DateTime.Now, DateTime.Now},
                    {"29","Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","1","9", DateTime.Now, DateTime.Now},
                    {"30","Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.","24","20", DateTime.Now, DateTime.Now},
                    {"31","Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.","22","14", DateTime.Now, DateTime.Now},
                    {"32","Mauris lacinia sapien quis libero.","46","9", DateTime.Now, DateTime.Now},
                    {"33","Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.","39","11", DateTime.Now, DateTime.Now},
                    {"34","Proin risus. Praesent lectus.","16","18", DateTime.Now, DateTime.Now},
                    {"35","Sed vel enim sit amet nunc viverra dapibus.","11","9", DateTime.Now, DateTime.Now},
                    {"36","Pellentesque eget nunc.","15","13", DateTime.Now, DateTime.Now},
                    {"37","Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","5","7", DateTime.Now, DateTime.Now},
                    {"38","Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","35","13", DateTime.Now, DateTime.Now},
                    {"39","Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.","5","11", DateTime.Now, DateTime.Now},
                    {"40","Integer tincidunt ante vel ipsum.","38","3", DateTime.Now, DateTime.Now},
                    {"41","Proin at turpis a pede posuere nonummy.","22","13", DateTime.Now, DateTime.Now},
                    {"42","Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.","5","9", DateTime.Now, DateTime.Now},
                    {"43","","7","15", DateTime.Now, DateTime.Now},
                    {"44","Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.","35","4", DateTime.Now, DateTime.Now},
                    {"45","Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.","18","12", DateTime.Now, DateTime.Now},
                    {"46","Praesent id massa id nisl venenatis lacinia.","10","3", DateTime.Now, DateTime.Now},
                    {"47","Duis mattis egestas metus.","35","19", DateTime.Now, DateTime.Now},
                    {"48","Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.","41","14", DateTime.Now, DateTime.Now},
                    {"49","Proin eu mi. Nulla ac enim.","41","18", DateTime.Now, DateTime.Now},
                    {"50","Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.","42","18", DateTime.Now, DateTime.Now},
                    {"51","Vivamus in felis eu sapien cursus vestibulum.","12","7", DateTime.Now, DateTime.Now},
                    {"52","In hac habitasse platea dictumst.","38","18", DateTime.Now, DateTime.Now},
                    {"53","Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.","20","9", DateTime.Now, DateTime.Now},
                    {"54","Pellentesque eget nunc.","47","5", DateTime.Now, DateTime.Now},
                    {"55","Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.","23","18", DateTime.Now, DateTime.Now},
                    {"56","Morbi quis tortor id nulla ultrices aliquet.","46","8", DateTime.Now, DateTime.Now},
                    {"57","Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.","11","9", DateTime.Now, DateTime.Now},
                    {"58","Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.","35","6", DateTime.Now, DateTime.Now},
                    {"59","Duis bibendum.","16","15", DateTime.Now, DateTime.Now},
                    {"60","Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","9","2", DateTime.Now, DateTime.Now},
                    {"61","Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.","23","6", DateTime.Now, DateTime.Now},
                    {"62","Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.","18","1", DateTime.Now, DateTime.Now},
                    {"63","Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.","17","20", DateTime.Now, DateTime.Now},
                    {"64","Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","20","18", DateTime.Now, DateTime.Now},
                    {"65","Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.","22","17", DateTime.Now, DateTime.Now},
                    {"66","Vivamus vestibulum sagittis sapien.","49","1", DateTime.Now, DateTime.Now},
                    {"67","Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.","10","8", DateTime.Now, DateTime.Now},
                    {"68","Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.","48","6", DateTime.Now, DateTime.Now},
                    {"69","Pellentesque at nulla. Suspendisse potenti.","11","12", DateTime.Now, DateTime.Now},
                    {"70","Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.","37","1", DateTime.Now, DateTime.Now},
                    {"71","Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.","40","6", DateTime.Now, DateTime.Now},
                    {"72","Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.","11","11", DateTime.Now, DateTime.Now},
                    {"73","Fusce consequat. Nulla nisl.","22","20", DateTime.Now, DateTime.Now},
                    {"74","Nulla facilisi. Cras non velit nec nisi vulputate nonummy.","13","6", DateTime.Now, DateTime.Now},
                    {"75","Etiam justo. Etiam pretium iaculis justo.","44","15", DateTime.Now, DateTime.Now},
                    {"76","Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.","27","16", DateTime.Now, DateTime.Now},
                    {"77","Donec semper sapien a libero. Nam dui.","26","16", DateTime.Now, DateTime.Now},
                    {"78","Nunc purus. Phasellus in felis. Donec semper sapien a libero.","21","1", DateTime.Now, DateTime.Now},
                    {"79","Praesent blandit. Nam nulla.","8","15", DateTime.Now, DateTime.Now},
                    {"80","Nunc purus. Phasellus in felis. Donec semper sapien a libero.","26","10", DateTime.Now, DateTime.Now},
                    {"81","Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.","40","10", DateTime.Now, DateTime.Now},
                    {"82","Morbi a ipsum.","27","2", DateTime.Now, DateTime.Now},
                    {"83","Phasellus in felis. Donec semper sapien a libero. Nam dui.","20","2", DateTime.Now, DateTime.Now},
                    {"84","Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.","9","11", DateTime.Now, DateTime.Now},
                    {"85","","49","6", DateTime.Now, DateTime.Now},
                    {"86","Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.","31","8", DateTime.Now, DateTime.Now},
                    {"87","Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.","49","16", DateTime.Now, DateTime.Now},
                    {"88","Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.","46","15", DateTime.Now, DateTime.Now},
                    {"89","Quisque ut erat.","26","6", DateTime.Now, DateTime.Now},
                    {"90","Duis mattis egestas metus. Aenean fermentum.","47","17", DateTime.Now, DateTime.Now},
                    {"91","Phasellus sit amet erat.","16","3", DateTime.Now, DateTime.Now},
                    {"92","Donec dapibus. Duis at velit eu est congue elementum.","50","10", DateTime.Now, DateTime.Now},
                    {"93","Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.","10","11", DateTime.Now, DateTime.Now},
                    {"94","Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.","7","17", DateTime.Now, DateTime.Now},
                    {"95","Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.","20","10", DateTime.Now, DateTime.Now},
                    {"96","Donec quis orci eget orci vehicula condimentum.","32","6", DateTime.Now, DateTime.Now},
                    {"97","Donec dapibus. Duis at velit eu est congue elementum.","5","19", DateTime.Now, DateTime.Now},
                    {"98","","6","12", DateTime.Now, DateTime.Now},
                    {"99","Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.","25","5", DateTime.Now, DateTime.Now},
                    {"100","Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.","40","14", DateTime.Now, DateTime.Now},
              });
        }
    }
}



